src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\DBAL\Types\Types;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: "user")]
//#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $prename = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(nullable: true)]
    private ?int $phone = null;

    #[ORM\Column(type: 'boolean', options: ['default' => false])]
    private $isVerified = false;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image;

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrename(): ?string
    {
        return $this->prename;
    }

    public function setPrename(string $prename): self
    {
        $this->prename = $prename;

        return $this;
    }

    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;
        return $this;
    }

    /**
     * A visual identifier that represents this user.
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';
        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;
        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;
        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

templates/security/login.html.twig
<!DOCTYPE html>
<html lang="fr" class="light-style customizer-hide" dir="ltr" data-theme="theme-default" data-assets-path="../assets/" data-template="vertical-menu-template-free">
	<head>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"/>
		<title>Login</title>
		<meta name="description" content=""/>
		<link rel="icon" type="image/x-icon" href="../assets/img/images/Logo-Cercle.png"/>
		<link rel="preconnect" href="https://fonts.googleapis.com"/>
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
		<link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet"/>
		<link rel="stylesheet" href="../assets/vendor/fonts/boxicons.css"/>
		<link rel="stylesheet" href="../assets/vendor/css/core.css" class="template-customizer-core-css"/>
		<link rel="stylesheet" href="../assets/vendor/css/theme-default.css" class="template-customizer-theme-css"/>
		<link rel="stylesheet" href="../assets/css/demo.css"/>
		<link rel="stylesheet" href="../assets/css/Styles.css"/>
		<link rel="stylesheet" href="../assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css"/>
		<link rel="stylesheet" href="../assets/vendor/css/pages/page-auth.css"/>
		<script src="../assets/vendor/js/helpers.js"></script>
		<script src="../assets/js/config.js"></script>
	</head>

	<body>
		<div class="container-xxl">
			<div class="authentication-wrapper authentication-basic container-p-y">
				<div class="authentication-inner">
					<div class="card">
						<div class="card-body">
							<a href="{{ path('app_homepage') }}">
								<div class="app-brand justify-content-center" style="margin-bottom: 1.5rem;">
									<img src="../assets/img/images/Logo-Cercle.png" alt="logo" class="app-brand-logo me-2" style="width: 81px;">
								</div>
							</a>
							<h4 class="mb-2">Bienvenue sur WanderWings! 👋</h4>
							<p class="mb-4">Veuillez vous connecter à votre compte et commencer l'aventure</p>
							<form id="formAuthentication" class="mb-3" method="POST">
								{% if error %}
									<div class="alert alert-warning alert-dismissible" role="alert">
										{{ error.messageKey|trans(error.messageData, 'security') }}
										<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
									</div>
									{% if app.user %}
										<div class="mb-3">
											<div class="alert alert-secondary" role="alert">Connecter en tant que
												{{ app.user.username }},
												<a href="{{ path('app_logout') }}">Logout</a>
											</div>
										</div>
									{% endif %}
								{% endif %}
								<div class="mb-3">
									<label for="email" class="form-label">Email</label>
									<input type="email" class="form-control" value="{{ last_username }}" id="email" name="email" placeholder="Enter votre Email" autofocus/>
								</div>
								<div class="mb-2 form-password-toggle">
									<div class="d-flex justify-content-between">
										<label class="form-label" for="password">Mot de passe</label>
										<a href="{# {{path('app_forgot_password_request')}} #}">
											<small>Mot de passe oublié?</small>
										</a>
									</div>
									<div class="input-group input-group-merge mb-4">
										<input type="password" id="password" class="form-control" name="password" placeholder="Enter votre mot de passe" aria-describedby="password"/>
										<span class="input-group-text cursor-pointer">
											<i class="bx bx-hide"></i>
										</span>
									</div>
									<input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
									<div class="mb-3">
										<button class="btn btn-primary d-grid w-100" type="submit">Connecter</button>
									</div>
								</form>
								<p class="text-center">
									<span>Nouveau sur notre plateforme ?</span>
									<a href="{{ path('app_register') }}">
										<span>Créer un compte</span>
									</a>
								</p>
							</div>
							<div class="divider my-4">
								<div class="divider-text">or</div>
							</div>
							<div class="d-flex justify-content-center">
								<a href="{# {{ path('fcb_login') }} #}" class="btn btn-icon btn-label-facebook me-3">
									<i class="tf-icons bx bxl-facebook"></i>
								</a>
								<a href="javascript:;" class="btn btn-icon btn-label-google-plus me-3">
									<i class="tf-icons bx bxl-google"></i>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			<script src="../assets/vendor/libs/jquery/jquery.js"></script>
			<script src="../assets/vendor/libs/popper/popper.js"></script>
			<script src="../assets/vendor/js/bootstrap.js"></script>
			<script src="../assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
			<script src="../assets/vendor/js/menu.js"></script>
			<script src="../assets/js/main.js"></script>
			<script async defer src="https://buttons.github.io/buttons.js"></script>
		</body>
	</body>
</html>

templates/security/register-done.html.twig
{# user/register-done.html.twig #}
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Confirmation Email</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style type="text/css">
  /**
   * Google webfonts. Recommended to include the .woff version for cross-client compatibility.
   */
  @media screen {
    @font-face {
      font-family: 'Source Sans Pro';
      font-style: normal;
      font-weight: 400;
      src: local('Source Sans Pro Regular'), local('SourceSansPro-Regular'), url(https://fonts.gstatic.com/s/sourcesanspro/v10/ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03otPbuUS0.woff) format('woff');
    }
    @font-face {
      font-family: 'Source Sans Pro';
      font-style: normal;
      font-weight: 700;
      src: local('Source Sans Pro Bold'), local('SourceSansPro-Bold'), url(https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGFkQc6VGVFSmCnC_l7QZG60.woff) format('woff');
    }
  }
  /**
   * Avoid browser level font resizing.
   * 1. Windows Mobile
   * 2. iOS / OSX
   */
  body,
  table,
  td,
  a {
    -ms-text-size-adjust: 100%; /* 1 */
    -webkit-text-size-adjust: 100%; /* 2 */
  }
  /**
   * Remove extra space added to tables and cells in Outlook.
   */
  table,
  td {
    mso-table-rspace: 0pt;
    mso-table-lspace: 0pt;
  }
  /**
   * Better fluid images in Internet Explorer.
   */
  img {
    -ms-interpolation-mode: bicubic;
  }
  /**
   * Remove blue links for iOS devices.
   */
  a[x-apple-data-detectors] {
    font-family: inherit !important;
    font-size: inherit !important;
    font-weight: inherit !important;
    line-height: inherit !important;
    color: inherit !important;
    text-decoration: none !important;
  }
  /**
   * Fix centering issues in Android 4.4.
   */
  div[style*="margin: 16px 0;"] {
    margin: 0 !important;
  }
  body {
    width: 100% !important;
    height: 100% !important;
    padding: 0 !important;
    margin: 0 !important;
  }
  /**
   * Collapse table borders to avoid space between cells.
   */
  table {
    border-collapse: collapse !important;
  }
  a {
    color: #1a82e2;
  }
  img {
    height: auto;
    line-height: 100%;
    text-decoration: none;
    border: 0;
    outline: none;
  }
  </style>

</head>
<body style="background-color: #e9ecef;">

  <!-- start preheader -->
  <div class="preheader" style="display: none; max-width: 0; max-height: 0; overflow: hidden; font-size: 1px; line-height: 1px; color: #fff; opacity: 0;">
    email de confirmation de compte pour Waves
  </div>
  <table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
      <td align="center" bgcolor="#e9ecef">
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
          <tr>
            <td align="left" bgcolor="#ffffff" style="padding: 36px 24px 0; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; border-top: 3px solid #d4dadf;">
              <h1 style="margin: 0; font-size: 32px; font-weight: 700; letter-spacing: -1px; line-height: 48px;">Confirmez votre adresse email</h1>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td align="center" bgcolor="#e9ecef">
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
          <tr>
            <td align="left" bgcolor="#ffffff" style="padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;">
              <p style="margin: 0;">Veuillez confirmer la création de votre compte pour accéder à notre site Web ci-dessous :</p>
            </td>
          </tr>
          <tr>
            <td align="left" bgcolor="#ffffff">
              <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                  <td align="center" bgcolor="#ffffff" style="padding: 12px;">
                    <table border="0" cellpadding="0" cellspacing="0">
                      <tr>
                        <td align="center" bgcolor="#1a82e2" style="border-radius: 6px;">
                          <a href="{{ signedUrl|raw }}" target="_blank" style="display: inline-block; padding: 16px 36px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; color: #ffffff; text-decoration: none; border-radius: 6px;">Activate now</a>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <tr>
            <td align="left" bgcolor="#ffffff" style="padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;">
              <p style="margin: 0;">Ce lien expirera dans {{ expiresAtMessageKey|trans(expiresAtMessageData, 'VerifyEmailBundle') }}</p>
            </td>
          </tr>
          <tr>
            <td align="left" bgcolor="#ffffff" style="padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px; border-bottom: 3px solid #d4dadf">
              <p style="margin: 0;">Regards,<br> HexaTech Team</p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>

templates/security/register.html.twig
<!DOCTYPE html>
<html lang="en" class="light-style customizer-hide" dir="ltr" data-theme="theme-default" data-assets-path="../assets/" data-template="vertical-menu-template-free">

	<head>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"/>
		<title>Register</title>
		<meta name="description" content=""/>
		<link rel="icon" type="image/x-icon" href="../assets/img/images/Logo-Cercle.png"/>
		<link rel="preconnect" href="https://fonts.googleapis.com"/>
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
		<link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet"/>
		<link rel="stylesheet" href="../assets/vendor/fonts/boxicons.css"/>
		<link rel="stylesheet" href="../assets/vendor/css/core.css" class="template-customizer-core-css"/>
		<link rel="stylesheet" href="../assets/vendor/css/theme-default.css" class="template-customizer-theme-css"/>
		<link rel="stylesheet" href="../assets/css/demo.css"/>
		<link rel="stylesheet" href="../assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css"/>
		<link rel="stylesheet" href="../assets/vendor/css/pages/page-auth.css"/>
		<script src="../assets/vendor/js/helpers.js"></script>
		<script src="../assets/js/config.js"></script>
		<script src="../js/pwdmeter.js"></script>
	</head>

	<body>
		<div class="container-xxl">
			<div class="authentication-wrapper authentication-basic container-p-y">
				<div class="authentication-inner" style="max-width: 540px">
					<div class="card">
						<div class="card-body">
							<a href="{{ path('app_homepage') }}">
								<div class="app-brand justify-content-center" style="margin-bottom: 1.5rem;">
									<img src="../assets/img/images/Logo-Cercle.png" alt="logo" class="app-brand-logo me-2" style="width: 81px;">
								</div>
							</a>
							<h4 class="mb-2">L'aventure commence ici 🚀</h4>
							<p class="mb-2">Encore plus proche</p>
							<form id="formAuthentication" class="mb-3" enctype="multipart/form-data" method="POST">
								{{ form_start(form) }}
								{% if form_errors(form) %}
									<div class="alert alert-warning alert-dismissible" role="alert">
										{{ form_errors(form) }}
										<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
									</div>
								{% endif %}
								<div class="row g-2 mb-3">
									<div class="col mb-0">
										{{form_row(form.name)}}
										{{form_errors(form.name)}}
									</div>
									<div class="col mb-0">
										{{form_row(form.prename)}}
										{{form_errors(form.prename)}}
									</div>
								</div>
								<div class="mb-3">
									{{ form_row(form.email) }}
									{{form_errors(form.image)}}
								</div>
								<div class="mb-2 form-password-toggle">
									{{ form_row(form.password, {'attr': {'id': 'passwordInput', 'oninput':'updatePasswordStrength(this.value)'}}) }}
									{{form_errors(form.password)}}
								</div>
								<div class="progress mb-3">
									<div id="PwdMeter" class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
								</div>
								<div class="mb-2">
									{{ form_row(form.phone) }}
									{{form_errors(form.phone)}}
								</div>
								<div class="mb-4">
									{{form_row(form.image)}}
									{{form_errors(form.image)}}
								</div>
								<button type="submit" class="btn btn-primary mb-3 d-grid w-100" id="signupButton" disabled>S'inscrire</button>
								<p class="text-center">
									<span>Vous avez déjà un compte?</span>
									<a href="{{ path('app_login') }}">
										<span>Connectez-vous</span>
									</a>
								</p>
							</div>
							{{ form_end(form) }}
						</form>
					</div>
				</div>
			</div>
		</div>
	</body>

</html></div><script src="../assets/vendor/libs/jquery/jquery.js"></script><script src="../assets/vendor/libs/popper/popper.js"></script><script src="../assets/vendor/js/bootstrap.js"></script><script src="../assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script><script src="../assets/vendor/js/menu.js"></script><script src="../assets/js/main.js"></script><script src="../assets/js/form-basic-inputs.js"></script><script async defer src="https://buttons.github.io/buttons.js"></script></body></html>