src/Entity/Traveler.php
<?php

namespace App\Entity;

use App\Repository\TravelerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TravelerRepository::class)]
class Traveler
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::BIGINT)]
    private ?string $num_pass = null;

    /**
     * @var Collection<int, Ticket>
     */
    #[ORM\OneToMany(targetEntity: Ticket::class, mappedBy: 'traveler')]
    private Collection $tickets;

    public function __construct()
    {
        $this->tickets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getNumPass(): ?string
    {
        return $this->num_pass;
    }

    public function setNumPass(string $num_pass): static
    {
        $this->num_pass = $num_pass;

        return $this;
    }

    /**
     * @return Collection<int, Ticket>
     */
    public function getTickets(): Collection
    {
        return $this->tickets;
    }

    public function addTicket(Ticket $ticket): static
    {
        if (!$this->tickets->contains($ticket)) {
            $this->tickets->add($ticket);
            $ticket->setTraveler($this);
        }

        return $this;
    }

    public function removeTicket(Ticket $ticket): static
    {
        if ($this->tickets->removeElement($ticket)) {
            // set the owning side to null (unless already changed)
            if ($ticket->getTraveler() === $this) {
                $ticket->setTraveler(null);
            }
        }

        return $this;
    }
}

src/Form/TravelerType.php
<?php

namespace App\Form;

use App\Entity\Traveler;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TravelerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('num_pass')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Traveler::class,
        ]);
    }
}

src/Controller/TravelerController.php
<?php

namespace App\Controller;

use App\Entity\Traveler;
use App\Form\TravelerType;
use App\Repository\TravelerRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/traveler')]
final class TravelerController extends AbstractController
{
    #[Route(name: 'app_traveler_index', methods: ['GET'])]
    public function index(TravelerRepository $travelerRepository): Response
    {
        return $this->render('traveler/index.html.twig', [
            'travelers' => $travelerRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_traveler_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $traveler = new Traveler();
        $form = $this->createForm(TravelerType::class, $traveler);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($traveler);
            $entityManager->flush();

            return $this->redirectToRoute('app_traveler_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('traveler/new.html.twig', [
            'traveler' => $traveler,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_traveler_show', methods: ['GET'])]
    public function show(Traveler $traveler): Response
    {
        return $this->render('traveler/show.html.twig', [
            'traveler' => $traveler,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_traveler_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Traveler $traveler, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TravelerType::class, $traveler);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_traveler_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('traveler/edit.html.twig', [
            'traveler' => $traveler,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_traveler_delete', methods: ['POST'])]
    public function delete(Request $request, Traveler $traveler, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$traveler->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($traveler);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_traveler_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/traveler/_delete_form.html.twig
<form method="post" action="{{ path('app_traveler_delete', {'id': traveler.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ traveler.id) }}">
    <button class="btn">Delete</button>
</form>

templates/traveler/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/traveler/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Traveler{% endblock %}

{% block body %}
    <h1>Edit Traveler</h1>

    {{ include('traveler/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_traveler_index') }}">back to list</a>

    {{ include('traveler/_delete_form.html.twig') }}
{% endblock %}

templates/traveler/index.html.twig
{% extends 'base.html.twig' %}
{% block tabletitle %} Travellers list {% endblock %}
{% block pagetitle %} <h2>Travellers</h2> {% endblock %}
{% block body %}
    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Num_pass</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for traveler in travelers %}
            <tr>
                <td>{{ traveler.id }}</td>
                <td>{{ traveler.name }}</td>
                <td>{{ traveler.numPass }}</td>
                <td>
                    <a href="{{ path('app_traveler_show', {'id': traveler.id}) }}" class="btn btn-primary">show</a>
                    <a href="{{ path('app_traveler_edit', {'id': traveler.id}) }}" class="btn btn-success">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_traveler_new') }}" class="btn btn-warning">Create new</a>
{% endblock %}

templates/traveler/new.html.twig
{% extends 'base.html.twig' %}

{% block tabletitle %} New Traveller {% endblock %}
{% block pagetitle %} <h2>Travellers</h2> {% endblock %}
{% block body %}
    {{ include('traveler/_form.html.twig') }}

    <a href="{{ path('app_traveler_index') }}" class="btn btn-primary">back to list</a>
{% endblock %}

templates/traveler/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Traveler{% endblock %}

{% block body %}
    <h1>Traveler</h1>

    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ traveler.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ traveler.name }}</td>
            </tr>
            <tr>
                <th>Num_pass</th>
                <td>{{ traveler.numPass }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_traveler_index') }}">back to list</a>

    <a href="{{ path('app_traveler_edit', {'id': traveler.id}) }}">edit</a>

    {{ include('traveler/_delete_form.html.twig') }}
{% endblock %}